name: DevSecOps Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: secure_api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest bandit pip-audit semgrep

      - name: Initialize database
        run: python init_db.py

      - name: Run Unit Tests
        env:
          PYTHONPATH: .
        run: |
          pytest ../tests -v

      - name: Run Bandit
        run: |
          bandit -r . \
          -x ./venv,./logs,./__pycache__,./automation,./security_automation \
          -f txt \
          -o bandit-report.txt
          EXIT_CODE=$?
          echo "===== BANDIT REPORT ====="
          cat bandit-report.txt

      - name: Dependency Scan
        run: |
          pip-audit -r requirements.txt | tee pip-audit-report.txt
          ls -lh pip-audit-report.txt
          cat pip-audit-report.txt
      - name: Build Docker Image
        run: |
          pwd
          ls -la
          docker build -t secure-api -f Dockerfile .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-api
          format: table
          output: trivy-report.txt
          severity: HIGH,CRITICAL
          exit-code: "0"
      - name: Verify Trivy report
        run: |
          pwd
          ls -lah
          ls -lh trivy-report.txt
          cat trivy-report.txt
      - name: Debug report locations
        run: |
          echo "Current directory:"
          pwd

          echo "Repository contents:"
          find .. -name "*report.txt"
      - name: Verify reports
        run: |
          pwd
          find . -name "*report.txt"

          echo "===== BANDIT ====="
          cat bandit-report.txt

          echo "===== PIP AUDIT ====="
          cat pip-audit-report.txt

          echo "===== TRIVY ====="
          cat trivy-report.txt
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
           secure_api/bandit-report.txt
           secure_api/pip-audit-report.txt
           secure_api/trivy-report.txt
